- id: '1608753473958'
  alias: 'Porch Light: On'
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: input_boolean.timer_porch
    state: 'on'
  action:
  - type: turn_on
    device_id: 15371c839a088f15441a41146da480b9
    entity_id: switch.porch_light
    domain: switch
  mode: single
- id: '1609212332962'
  alias: 'Porch Light: Off'
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.timer_porch
    state: 'on'
  action:
  - type: turn_off
    device_id: 15371c839a088f15441a41146da480b9
    entity_id: switch.porch_light
    domain: switch
  mode: single
- id: '1609516471011'
  alias: 'Master Bath: 1 Low'
  description: ''
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.master_bath_light
      node_id: 15
      scene_data: 7680
      scene_id: 3
  condition: []
  action:
  - type: turn_on
    device_id: 59ed4f9e1e0bf67641b76364515495aa
    entity_id: light.master_bath_light
    domain: light
    brightness_pct: 50
  mode: single
- id: '1609516804056'
  alias: Good Night
  description: ''
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.master_bedroom_light
      node_id: 14
      scene_data: 3
      scene_id: 1
  condition: []
  action:
  - scene: scene.good_night
  mode: single
- id: '1609525222269'
  alias: 'Master Bath: 2 Medium'
  description: ''
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.master_bath_light
      node_id: 15
      scene_data: 7860
      scene_id: 2
  condition: []
  action:
  - type: turn_on
    device_id: 59ed4f9e1e0bf67641b76364515495aa
    entity_id: light.master_bath_light
    domain: light
    brightness_pct: 80
  mode: single
- id: '1609525247708'
  alias: 'Master Bath: 3 High'
  description: ''
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.master_bath_light
      node_id: 15
      scene_data: 7920
      scene_id: 2
  condition: []
  action:
  - type: turn_on
    device_id: 59ed4f9e1e0bf67641b76364515495aa
    entity_id: light.master_bath_light
    domain: light
    brightness_pct: 100
  mode: single
- id: '1609726220058'
  alias: 'Barn Door Protocol: Activate'
  description: ''
  trigger:
  - platform: state
    entity_id: group.exterior
    to: 'on'
    for: 00:10:00
  condition:
  - condition: state
    entity_id: input_boolean.barn_door_protocol
    state: 'off'
  - condition: device
    device_id: 3a4702e5f54b52ded08ab1b7002dcab0
    domain: climate
    entity_id: climate.ecobee3
    type: is_hvac_mode
    hvac_mode: heat
  action:
  - device_id: 3a4702e5f54b52ded08ab1b7002dcab0
    domain: climate
    entity_id: climate.ecobee3
    type: set_hvac_mode
    hvac_mode: 'off'
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.barn_door_protocol
  mode: single
- id: '1609726335791'
  alias: 'Barn Door Protocol: Deactivate'
  description: Turn furnace heat back on when doors have all closed
  trigger:
  - platform: state
    entity_id: group.exterior
    to: 'on'
    for: 00:05:00
  condition:
  - condition: state
    entity_id: input_boolean.barn_door_protocol
    state: 'on'
  action:
  - device_id: 3a4702e5f54b52ded08ab1b7002dcab0
    domain: climate
    entity_id: climate.ecobee3
    type: set_hvac_mode
    hvac_mode: heat
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.barn_door_protocol
  mode: single
- id: '1618699479074'
  alias: 'Den Tablet: Outlet Power Toggle'
  description: ''
  trigger:
  - platform: state
    to: 'on'
    for: 03:00:00
    entity_id: switch.dlink_w110
  - platform: state
    entity_id: switch.dlink_w110
    to: 'off'
    for: 01:00:00
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.dlink_w110
  mode: single
- id: '1618931305830'
  alias: Heartworm Meds Due
  description: ''
  trigger:
  - platform: template
    value_template: '{{ now().day == 15 }}'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.heartworm_needed
  mode: single
- id: '1622671166530'
  alias: Unexpected Entry
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: b3d3b805c7fd15e7c38179aeb21df064
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: d235c5737493c72d37c4a73db6d15629
    entity_id: binary_sensor.garage_door_sensor
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: b62d5ca6541f93ae5a5d8bcc9f870873
    entity_id: binary_sensor.back_door
    domain: binary_sensor
  condition:
  - condition: time
    after: '22:00:00'
    before: 06:00:00
  - condition: state
    entity_id: input_select.presence_mode
    state: Away
  action:
  - service: notify.telegram_tom
    data:
      title: Unexpected Entry!
      message: '{{trigger.to_state.attributes.friendly_name }} opened at night...'
  mode: single
- id: '1624219701132'
  alias: Hass Shutdown Switch
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.shutdown_confirm
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.shutdown_confirm
      - input_boolean.shutdown_primer
  - service: hassio.host_shutdown
  mode: single
- id: '1625264068184'
  alias: Plex Button
  description: ''
  trigger:
  - device_id: c41a7cabdaf68d062d0fa206dfe908cb
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition:
  - condition: template
    value_template: '{{ state_attr(''media_player.fire_tv'', ''source'') != ''Plex''
      }}'
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.fire_tv
  - service: androidtv.adb_command
    data:
      entity_id: media_player.fire_tv
      command: ' am start -a android.intent.action.VIEW -n   com.plexapp.android/com.plexapp.plex.activities.SplashActivity'
  mode: single
- id: '1626486666380'
  alias: Den Light Dimmer
  description: ''
  use_blueprint:
    path: poolcactus/zha-ikea-tradfri-on-off-switch-incl-dimmer.yaml
    input:
      remote: 84350b6f41b7cad45266de52c9f7b34b
      light:
        entity_id:
        - light.den_light_1
        - light.den_light_2
- id: '1628346244000'
  alias: Living Room Light Button
  description: ''
  use_blueprint:
    path: poolcactus/zha-ikea-tradfri-on-off-switch-incl-dimmer.yaml
    input:
      remote: 72b251a428277f7ce1b4de58b20344b5
      light:
        entity_id: light.living_room_light
- id: '1629823138157'
  alias: Speed Tests
  description: ''
  trigger:
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - service: speedtestdotnet.speedtest
  mode: single
- id: '1632795665418'
  alias: 'Living Room TV: Reboot'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.fire_tv_reboot
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.fire_tv_reboot
  - service: androidtv.adb_command
    data:
      entity_id: media_player.fire_tv
      command: reboot
  mode: single
