##########################################################
## Time of Day
##########################################################

- platform: tod
  name: Sundown
  after: sunset
  before: sunrise
  before_offset: "-00:30"

##########################################################
## Template Sensors
##########################################################

- platform: template
  sensors:

    trashday:
      friendly_name: Trash Pickup
      value_template: >
        {{ state_attr('sensor.trash_service','prox')|float == 0 }}
      attribute_templates:
        type: >
          {{ state_attr('sensor.trash_service','desc') }}
        proximity: >
          {{ state_attr('sensor.trash_service','prox') }}
        date: >
          {{ state_attr('sensor.trash_service','when') }}
      icon_template: >
        {% if state_attr('sensor.trash_service','type') == 'both' %}
          mdi:recycle
        {% else %}
          mdi:delete
        {% endif %}

    laundry_washer:
      friendly_name: "Washing Machine"
      # delay_on: Value condition must be true for this long before the sensor switches ON
      delay_on:
        minutes: 2
      # delay_off: Value condition must be false for this long before the sensor switches OFF
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.washing_machine_outlet_power')|float > 5 }}
      icon_template: >
        mdi:washing-machine
    laundry_dryer:
      friendly_name: "Clothes Dryer"
      # delay_off: Value condition must be false for this long before the sensor switches OFF
      delay_off:
        minutes: 2
      value_template: >-
        {{ states('sensor.dryer_sensor_temperature')|float > 75 }}
      icon_template: >
        mdi:tumble-dryer

    monthly_data_concern:
      friendly_name: Data Cap Issue
      value_template: >
        {{ states('sensor.monthly_data_cap')|float >= states('sensor.month_gone')|float }}
      icon_template: >
        {% if is_state('binary_sensor.monthly_data_concern','on') %}
          mdi:alert-circle-outline
        {% else %}
          mdi:thumb-up
        {% endif %}

    hallway_motion:
      friendly_name: "Hallway Motion"
      value_template: >-
        {{ is_state('binary_sensor.fibaro_motion_1_any', 'on') or
           is_state('binary_sensor.fibaro_motion_2_any', 'on') }}
      device_class: motion
      icon_template: >
        {% if is_state('binary_sensor.hallway_motion','on') %}
          mdi:motion-sensor
        {% else %}
          mdi:motion-sensor-off
        {% endif %}

##########################################################
## Network Devices
##########################################################

- platform: ping
  host: !secret nas_host
  name: DS420j Online

- platform: ping
  host: !secret pizero_host
  name: Raspberry Pi Zero Online


##########################################################
## Presence Detection
##########################################################

- platform: bayesian
  prior: 0.5
  name: 'Tom Presence'
  probability_threshold: 0.8
  observations:
    - entity_id: 'device_tracker.keys'
      prob_given_true: 0.7 #likelihood i'm home if this is true
      prob_given_false: 0.2 #likelihood this shows as home when i'm not
      platform: 'state'
      to_state: 'home'
    - entity_id: 'sensor.iphone_ssid'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'Aether'
