##########################################################
## Template Sensors
##########################################################

#- platform: template
#  sensors:

#    laundry_washer:
#      friendly_name: "Washing Machine"
#      # delay_on: Value condition must be true for this long before the sensor switches ON
#      delay_on:
#        minutes: 2
      # delay_off: Value condition must be false for this long before the sensor switches OFF
#      delay_off:
#        minutes: 3
#      value_template: >-
#        {{ states('sensor.washing_machine_outlet_power')|float > 5 }}
#      icon_template: >
#        mdi:washing-machine


##########################################################
## Trendlines
##########################################################



##########################################################
## Network Devices
##########################################################

- platform: command_line
  name: "Plex Ping"
  command: 'response=$(curl -LIk 192.168.1.202:32400 -o /dev/null -w "%{http_code}\n" -s); test "$response" -ge 200 && echo "ON" || echo "OFF"'
  device_class: connectivity
  scan_interval: 60
  payload_on: 'ON'
  payload_off: 'OFF'

- platform: ping
  host: !secret shield_ip
  name: Shield Online
  scan_interval: 3600
  count: 2

- platform: ping
  host: !secret nas_host
  name: DS420j Online
  scan_interval: 3600
  count: 2

- platform: ping
  host: !secret pizero_host
  name: Raspberry Pi Zero Online
  scan_interval: 3600
  count: 2
