- platform: template
  sensors:

    trashday:
        friendly_name: Trash Pickup
        value_template: >
          {{ state_attr('sensor.trash_service','prox')|float == 0 }}
        attribute_templates:
          type: >
            {{ state_attr('sensor.trash_service','desc') }}
          proximity: >
            {{ state_attr('sensor.trash_service','prox') }}
          date: >
            {{ state_attr('sensor.trash_service','when') }}
        icon_template: >
          {% if state_attr('sensor.trash_service','type') == 'both' %}
            mdi:recycle
          {% else %}
            mdi:delete
          {% endif %}

    laundry_washer:
      friendly_name: "Washing Machine"
      # delay_on: Value condition must be true for this long before the sensor switches ON
      delay_on:
        minutes: 2
      # delay_off: Value condition must be false for this long before the sensor switches OFF
      delay_off:
        minutes: 3
      value_template: >-
        {{ states('sensor.washing_machine_outlet_power')|float > 5 }}
      icon_template: >
        mdi:washing-machine
    laundry_dryer:
      friendly_name: "Clothes Dryer"
      # delay_off: Value condition must be false for this long before the sensor switches OFF
      delay_off:
        minutes: 2
      value_template: >-
        {{ states('sensor.dryer_sensor_temperature')|float > 75 }}
      icon_template: >
        mdi:tumble-dryer

- platform: ping
  host: !secret nas_host
  name: DS420j Online

- platform: ping
  host: !secret pizero_host
  name: Raspberry Pi Zero Online
