
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_domain:
    climate:
      precision: 1.0
  allowlist_external_dirs:
    - /config
  time_zone: America/Denver


# Outsource configurations to sub-files:
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
command_line: !include command_line.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
multiscrape: !include multiscrape.yaml
recorder: !include recorder.yaml
rest: !include rest.yaml
#scrape: !include scrape.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
template: !include template.yaml

frontend:
  themes: !include_dir_merge_named themes


# Notifications

notify:
  - name: telegram_tom
    platform: telegram
    chat_id: !secret telegram_chatid_tom
telegram_bot:
- platform: polling
  api_key: !secret telegram_bot_token
  allowed_chat_ids:
  - !secret telegram_chatid_tom


rest_command:
  ombi_approve_tv:
    url: !secret ombi_approve_tv
    method: post # must be POST for approvals
    content_type: "application/json"
    headers:
        apikey: !secret ombi_apikey
    payload: '{{ payload_data | tojson }}'
  ombi_deny_tv:
    url: !secret ombi_deny_tv
    method: put # must be PUT for denials
    content_type: "application/json"
    headers:
        apikey: !secret ombi_apikey
    payload: '{{ payload_data | tojson }}'


panel_custom:
  - name: zwave-graph-panel
    url_path: zwave-graph
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph3.js
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave

ios:
  actions:
    - name: Pause Tautulli
      background_color: "#000000" # Requires `use_custom_colors`
      label:
        text: "Mute Tautulli"
        color: "#ffffff" # Requires `use_custom_colors`
      icon:
        icon: mdi:pause-circle
        color: "#ffffff"
      show_in_carplay: true
      show_in_watch: false
      use_custom_colors: true


# Text to speech
tts:
  - platform: google_translate

cloud:


zha:
  zigpy_config:
    network:
      channel: 15 # What channel the radio should try to use.
      channels: [15, 20, 25] # Channel mask
    ota:
      otau_directory: /config/zigpy_ota

logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.zha: debug
    bellows.zigbee.application: info
    bellows.ezsp: info
    zigpy: debug
    zigpy_cc: info
    zigpy_deconz.zigbee.application: info
    zigpy_deconz.api: info
    zigpy_xbee.zigbee.application: info
    zigpy_xbee.api: info

    zigpy_zigate: info
    zigpy_znp: info
    zhaquirks: info
