
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config


# Text to speech
tts:
  - platform: google_translate

cloud:

wake_on_lan:

# Outsource configurations to sub-files:
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
recorder: !include recorder.yaml
sensor: !include sensors.yaml
template: !include template.yaml


frontend:
  themes: !include_dir_merge_named themes
          
logger:
  default: error
  logs:
    homeassistant.components.zha: debug

# Notifications
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - !secret telegram_chatid_tom

notify:
  - name: telegram_tom
    platform: telegram
    chat_id: !secret telegram_chatid_tom

rest_command:
  check_monthly_data:
    url: !secret my_datausage_source
    method: GET
    verify_ssl: false

panel_custom:
  - name: zwave-graph-panel
    url_path: zwave-graph
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph3.js
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave

