- platform: androidtv
  name: Nvidia Shield
  device_class: androidtv
  screencap: false
  host: 10.0.0.100
  exclude_unnamed_apps: false
- platform: androidtv
  name: Den TV
  device_class: firetv
  screencap: false
  host: 10.0.0.102
  apps:
    com.amazon.tv.launcher: "Fire TV"
    com.plexapp.android: "Plex"
    com.sm.SlingGuide.Dish: "DISH Anywhere"
    com.hbo.hbonow: "HBO"
    com.hulu.livingroomplus: "Hulu"
    com.cbs.ott: "CBS All Access"
  exclude_unnamed_apps: false
  state_detection_rules:
    'com.amazon.tv.launcher':
      - 'standby'
    'com.netflix.ninja':
      - 'media_session_state'
    'com.plexapp.android':
      - 'paused':
          'media_session_state': 3
          'wake_lock_size': 1
      - 'playing':
          'media_session_state': 3
      - 'standby'
    'com.amazon.avod':
      - 'playing':
          'wake_lock_size': 4
      - 'playing':
          'wake_lock_size': 3
      - 'paused':
          'wake_lock_size': 2
      - 'paused':
          'wake_lock_size': 1
      - 'standby'
