# SYSTEM MONITOR
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: processor_temperature
    - type: memory_use_percent
    - type: disk_use_percent
      arg: "/"
    - type: last_boot
    - type: network_in
      arg: "eth0"
    - type: network_out
      arg: "eth0"

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: derivative
  source: sensor.data_usage_gb
  name: Data Usage Per Hour
  round: 1
  unit_time: h
  time_window: "01:00:00"

- platform: min_max
  unique_id: inside_temp_average
  name: Inside Temp Average
  entity_ids:
    - sensor.ecobee3_temperature
    - sensor.ecobee_bedroom_temperature
    - sensor.ecobee_den_temperature
  type: mean


####################
#
# REST SENSORS
#
####################

# PLEX SERVER: OPEN HARDWARE MONITOR
- platform: rest
  resource: !secret scylla_ohm
  name: Scylla OHM
  scan_interval: 300
  json_attributes_path: "$.Children[0]"
  json_attributes:
    - Children
  value_template: "{{ now() }}"


- platform: rest
  resource: !secret my_trashservice_url
  name: "Trash Pickup Data"
  unique_id: trash_pickup_data
  icon: mdi:delete
  scan_interval: 3600
  json_attributes:
    - current
    - next
  value_template: '{{ value_json.updated }}'


# AIR QUALITY MONITOR sourced from AirVisual
- platform: rest
  resource: !secret my_aqi_url
  unique_id: airquality_api
  name: "AirVisual Data"
  scan_interval: 3600
  json_attributes_path: "$.data.current.pollution"
  json_attributes:
    - ts
    - aqius
    - mainus
  value_template: '{{ value_json.data.current.pollution.aqius }}'
  device_class: aqi

- platform: rest
  resource: !secret sunrise_today_url
  unique_id: sunrise_api_today
  name: Sunrise Data Today
  scan_interval: 14400
  value_template: '{{ value_json.status }}'
  json_attributes_path: "$.results"
  json_attributes:
    - sunrise
    - sunset
- platform: rest
  resource: !secret sunrise_tmrw_url
  unique_id: sunrise_api_tmrw
  name: Sunrise Data Tomorrow
  scan_interval: 14400
  value_template: '{{ value_json.status }}'
  json_attributes_path: "$.results"
  json_attributes:
    - sunrise
    - sunset

# WEATHER REPORT sourced from OpenWeatherMap
- platform: rest
  resource: !secret my_weather_url
  unique_id: weather_api
  name: Weather Report
  scan_interval: 1800
  json_attributes:
    - temp
    - feels_like
    - condition
    - condition_icon
  value_template: '{{ value_json.condition }}'


