- platform: rest
  resource: !secret my_airquality_url
  name: "AQI Report"
  scan_interval: 3600
  json_attributes:
    - aqi
    - desc
    - upd
    - fetched
- platform: rest
  name: owm_report
  json_attributes:
    - current
    - tomorrow
  value_template: '{{ value_json["current"]["cond"] }}'
  resource: !secret my_weather_url
- platform: tautulli
  api_key: !secret tautulli_token
  host: !secret tautulli_host
  port: 8181
- platform: template
  sensors:
    airquality:
        friendly_name: Air Quality
        unique_id: airquality
        value_template: >
          {{ state_attr('sensor.aqi_report','desc') }}
        attribute_templates:
          AQI: >
            {{ state_attr('sensor.aqi_report','aqi') }}
          upd: >
            {{ state_attr('sensor.aqi_report','fetched') }}
    trafficmeter:
        friendly_name: Traffic Meter
        unique_id: trafficmeter
        icon_template: 'mdi:gauge'
        unit_of_measurement: 'GB'
        value_template: >
          {{ states.input_number.trafficmeter_usage.state }}
    trafficmeter_pct:
        friendly_name: 'Traffic Meter: Percent of Cap'
        unique_id: trafficmeterpct
        icon_template: 'mdi:gauge'
        unit_of_measurement: '%'
        value_template: >
          {{ states.input_number.trafficmeter_percent.state }}
    trash_pickup:
        friendly_name: Trash Pickup
        value_template: >
          {{ states.input_text.trash_pickup_date.state }}
        attribute_templates:
          proximity: >
            {{ states.input_number.trash_daystil.state }}
          type: >
            {% if states.input_boolean.trash_recycling.state == 'on' %}
              Trash & Recycling
            {% else %}
              Trash Pickup
            {% endif %}
        icon_template: >
          {% if states.input_boolean.trash_recycling.state == 'on' %}
            mdi:recycle
          {% else %}
            mdi:delete
          {% endif %}
- platform: nut
  name: APC UPS
  host: !secret nas_host
  resources:
    - ups.status.display
    - battery.charge
    - battery.charge.warning
    - battery.charge.low
    - battery.runtime
    - ups.timer.reboot
    - ups.timer.shutdown
