# SYSTEM MONITOR
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: processor_temperature
    - type: memory_use_percent
    - type: disk_use_percent
      arg: "/"
    - type: last_boot
    - type: network_in
      arg: "eth0"
    - type: network_out
      arg: "eth0"

- platform: time_date
  display_options:
    - 'time'
    - 'date'

  
####################
#
# REST SENSORS
#
####################

# PLEX SERVER: OPEN HARDWARE MONITOR
- platform: rest
  resource: !secret scylla_ohm
  name: Scylla OHM
  scan_interval: 300
  json_attributes_path: "$.Children[0]"
  json_attributes:
    - Children
  value_template: "{{ now() }}"

# PLEX SERVER: TAUTULLI STREAMS
- platform: rest
  resource: !secret tautulli_api_streams
  name: "Plex Streams"
# scan every 10 minutes
  scan_interval: 600
  json_attributes_path: "$.response.data"
  json_attributes:
    - stream_count_direct_play
    - stream_count_direct_stream
    - stream_count_transcode
  value_template: '{{ value_json.response.data.stream_count }}'
  state_class: measurement

# PLEX SERVER: TAUTULLI LIBRARIES
- platform: rest
  resource: !secret tautulli_api_libs
  name: "Plex Libraries"
# scan every 24 hours
  scan_interval: 86400
  json_attributes_path: "$.response"
  json_attributes:
    - data
  value_template: '{{ value_json.response.result }}'

# TRASH PICKUP SERVICE
- platform: rest
  resource: !secret my_trashpickup_url
  name: "Trash Service"
# scan every 6 hours
  scan_interval: 21600
  json_attributes:
    - date
    - desc
    - type
    - prox
    - when
  value_template: "{{ value_json.desc }}"

# ROUTER-BASED DATA MONITOR
- platform: rest
  resource: !secret my_datausage_url
  name: "Monthly Data Report"
  scan_interval: 42300
  json_attributes:
    - pct_of_month
    - gb
    - pct_of_cap
    - concern
    - updated
  value_template: "{{ value_json.pct_of_cap|float }}"
  unit_of_measurement: "%"
  state_class: total_increasing

# AIR QUALITY MONITOR sourced from AirVisual
- platform: rest
  resource: !secret my_airquality_url
  name: "AirVisual Data"
  scan_interval: 3600
  json_attributes_path: "$.data.current.pollution"
  json_attributes:
    - ts
    - aqius
    - mainus
  value_template: '{{ value_json.data.current.pollution.aqius }}'
  device_class: aqi

# WEATHER REPORT sourced from OpenWeatherMap
- platform: rest
  resource: !secret my_weather_url
  name: Weather Report
  scan_interval: 1800
  json_attributes:
    - temp
    - feels_like
    - condition
    - condition_icon
  value_template: '{{ value_json.condition }}'

# POLLEN REPORT sourced from tomorrow.io
- platform: rest
  resource: !secret my_pollen_url
  name: Pollen Data
  scan_interval: 3600
  json_attributes_path: "$.data.timelines[0].intervals[0].values"
  json_attributes:
    - grassIndex
    - treeIndex
    - weedIndex
  value_template: >
    {% set grass = value_json.data.timelines[0].intervals[0]['values']['grassIndex'] %}
    {% set trees = value_json.data.timelines[0].intervals[0]['values']['treeIndex'] %}
    {% set weeds = value_json.data.timelines[0].intervals[0]['values']['weedIndex'] %}
    {{ max(grass,trees,weeds) }}


