- platform: rest
  resource: !secret my_trashpickup_url
  name: "Trash Service"
  scan_interval: 3600
  json_attributes:
    - date
    - desc
    - type
    - prox
    - when
  value_template: "{{ value_json.desc }}"

- platform: rest
  resource: !secret my_datausage_url
  name: "Monthly Data Usage"
  scan_interval: 3600
  json_attributes:
    - used
    - per
    - upd
  value_template: "{{ value_json.used }}"
  unit_of_measurement: "GB"

- platform: rest
  resource: !secret my_airquality_url
  name: "AQI Report"
  scan_interval: 3600
  json_attributes:
    - aqi
    - desc
    - upd
    - fetched

- platform: template
  sensors:
    trashday:
        friendly_name: Trash Pickup
        value_template: >
          {{ state_attr('sensor.trash_service','when') }}
        attribute_templates:
          type: >
            {{ state_attr('sensor.trash_service','desc') }}
          proximity: >
            {{ state_attr('sensor.trash_service','prox') }}
        icon_template: >
          {% if state_attr('sensor.trash_service','type') == 'both' %}
            mdi:recycle
          {% else %}
            mdi:delete
          {% endif %}

    monthly_data_cap:
        friendly_name: Data Cap Usage
        value_template: >
          {{ state_attr('sensor.monthly_data_usage','used') }}
        unit_of_measurement: "%"
        attribute_templates:
          updated: >
            {{ state_attr('sensor.monthly_data_usage','upd') }}
        icon_template: 'mdi:label-percent'

    airvisual:
        friendly_name: AirVisual
        unique_id: airvisual
        value_template: >
          {{ state_attr('sensor.airvisual_api','aqi') }}
        attribute_templates:
          upd: >
            {{ state_attr('sensor.airvisual_api','ts') }}

    airquality:
        friendly_name: Air Quality
        unique_id: airquality
        value_template: >
          {{ state_attr('sensor.aqi_report','desc') }}
        attribute_templates:
          AQI: >
            {{ state_attr('sensor.aqi_report','aqi') }}
          upd: >
            {{ state_attr('sensor.aqi_report','fetched') }}

    month_days:
        friendly_name: Days This Month
        value_template: >
          {% if now().month in [1,3,5,7,8,10,12] %}
            31
          {% elif now().month in [4,6,9,11] %}
            30
          {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
            28
          {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
            29
          {% endif %}


